//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanzasPersonales.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinanzasPersonales : DbContext
    {
        public FinanzasPersonales()
            : base("name=FinanzasPersonales")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Categoria_gasto> t_Categoria_gasto { get; set; }
        public virtual DbSet<t_Gastos> t_Gastos { get; set; }
        public virtual DbSet<t_cuenta_pres> t_cuenta_pres { get; set; }
        public virtual DbSet<t_presupuesto> t_presupuesto { get; set; }
    }
}
